on:
  push:
    branches: [ master ]
  pull_request:
  merge_group:

name: Code formatting check

jobs:
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update Rust toolchain
        run: rustup update stable && rustup default stable
      - name: Check code formatting
        run: cargo fmt --all -- --check --verbose
